tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "coreutils"
brew "docker-completion"
brew "fish"
brew "git"
brew "iproute2mac"
brew "mas"
brew "mosh"
brew "mtr"
brew "nmap"
brew "node"
brew "stow"
brew "telnet"
brew "tree"
brew "vim"
brew "wine"
cask "1password"
cask "discord"
cask "docker"
cask "dropbox"
cask "evernote"
cask "firefox"
cask "google-chrome"
cask "iterm2"
cask "keka"
cask "kobo"
cask "microsoft-teams"
cask "quip"
cask "steam"
cask "telegram"
cask "visual-studio-code"
cask "wireshark"
mas "Bear", id: 1091189122
mas "Microsoft OneNote", id: 784801555
mas "Microsoft Outlook", id: 985367838
mas "OneDrive", id: 823766827
mas "Pocket", id: 568494494
mas "Slack", id: 803453959
mas "Trello", id: 1278508951
